function createvoltagecloudfigure(X1, Y1, X2, Y2)
%CREATEFIGURE(X1, Y1, X2, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 19-Nov-2015 21:39:49

% Create figure
figure1 = figure('Name','Voltage vs. Cloud Cover');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create datetime plot
plot(X1,Y1,'Parent',axes1,'DisplayName','Voltage');

% Create ylabel
ylabel('Voltage');

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[736272.7 736288.3]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[10 20]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'YColor',[0 0.447 0.741],'YTick',[10 15 20]);
% Create axes
axes2 = axes('Parent',figure1,...
    'ColorOrder',[0.85 0.325 0.098;0.929 0.694 0.125;0.494 0.184 0.556;0.466 0.674 0.188;0.301 0.745 0.933;0.635 0.078 0.184;0 0.447 0.741],...
    'Position',[0.13 0.11 0.775 0.815]);
hold(axes2,'on');

% Create datetime plot
plot(X2,Y2,'Parent',axes2,'DisplayName','% CloudCover');

% Create ylabel
ylabel('Percent Cloud Cover');

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[736272.7 736288.3]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0 100]);
% Set the remaining axes properties
set(axes2,'Color','none','HitTest','off','YAxisLocation','right','YColor',...
    [0.85 0.325 0.098],'YTick',[0 50 100]);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.2335743045388 0.77979274611399 0.0782851390922404 0.0829015544041457]);

